name: Go lint and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.23.2'
          cache: false
          args: --timeout=10m -v

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout=10m -v
          version: v1.61.0

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.2'
          cache: false

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run golang test
        run: go test -gcflags='-l -h' -v ./...
